# Porta do servidor
server.port=9090

# Ativa o endpoint de shutdown
management.endpoint.shutdown.enabled=true
management.endpoints.web.exposure.include=health,info,shutdown

# Documentação Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Configuração de Inatividade (padrão 0 = desativado)
server.inactivity-timeout=0
